import os
import shutil

import template
import page

def process(project, project_id):
    project_name = project["name"].replace(" ", "_")

    routes = {}
    default_route = None

    if 'pages' in project:
        for page_id in project['pages']:
            page_name = project['pages'][page_id]['name'].replace(" ", "_")
            template_id = project['pages'][page_id]['template']
            template_name = project['templates'][template_id]['name'].replace(" ", "_")
            default = True # project['pages'][page_id]['default']

            routes[page_name] = [template_name, page_name]

            if default:
                default_route = page_name


    Write(project_name, default_route, routes)
 
def Write(project_name, default_route, routes):
    with open(f"build/{project_name}/assets/components/routes.js", "w") as f:

        f.write(f"""
// routes.js, Made for {project_name}
// Generated By Lekho Website
m.route(document.body, "{default_route}", {{
        """)

        for route in routes:
            f.write(f"""
        "/{route}": {{
            view: function() {{
                return m({routes[route][0]}, m({routes[route][1]}))
            }}
        }},
        """
         )

        f.write(f"""
    }})
        """)